### ISSUE TITLE
Weather not displaying correctly

### ISSUE THREAD

**Issue by PeterStrick** [cairoshell/CairoExtensionSamples#1]
I don´t think it´s 1692° in Vienna, Austria
This is not Fahrenheit because if it were, then it is 999° and I would probably be dead either way.
It shouuld be 17°C or 62 Fahrenheit like it´s in the MSN weather app.

Pressure, Humidity and Wind meters are fine.

Screenshot provided here: 
![image](https://user-images.githubusercontent.com/60312421/84599086-bb961700-ae6f-11ea-8c6b-229fef790446.png)

**Comment by dremin** [comment]
I tried testing this by putting in the latitude/longitude of Vienna but I see the correct results. Maybe OpenWeatherMap was returning bad data? Is this still returning bad data for you?

**Comment by PeterStrick** [comment]
Will check it out again when im home.

**Comment by josuave** [comment]
Is this still an issue?
